package com.sgerrand.paymentcardutil.iso8583;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.databind.JsonNode;
import com.sgerrand.paymentcardutil.vectors.Vectors;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * Checks this library against messages produced by the Python cardutil package.
 *
 * <p>Each case was generated by running cardutil itself, so a failure here means the Java port and
 * the Python original disagree, not that a hand written expectation is stale.
 */
class Iso8583ParityTest {

    @TestFactory
    @DisplayName("serializing matches cardutil byte for byte")
    Stream<DynamicTest> serializeMatchesCardutil() {
        return Vectors.tests(
                "iso8583",
                testCase -> {
                    Iso8583Message message =
                            Iso8583Message.of(Vectors.values(testCase.get("input")));
                    byte[] actual = Iso8583.serialize(message, options(testCase));
                    assertEquals(testCase.get("message_hex").asText(), Vectors.hex(actual));
                });
    }

    @TestFactory
    @DisplayName("parsing gives the same values as cardutil")
    Stream<DynamicTest> parseMatchesCardutil() {
        return Vectors.tests(
                "iso8583",
                testCase -> {
                    byte[] raw = Vectors.hex(testCase.get("message_hex").asText());
                    Iso8583Message parsed = Iso8583.parse(raw, options(testCase));
                    Vectors.assertValuesEqual(
                            Vectors.values(testCase.get("parsed")), parsed.values());
                });
    }

    @TestFactory
    @DisplayName("a parsed message writes back to the same bytes")
    Stream<DynamicTest> roundTrip() {
        return Vectors.tests(
                "iso8583",
                testCase -> {
                    String expected = testCase.get("message_hex").asText();
                    Iso8583Options options = options(testCase);
                    Iso8583Message parsed = Iso8583.parse(Vectors.hex(expected), options);
                    assertEquals(expected, Vectors.hex(Iso8583.serialize(parsed, options)));
                });
    }

    private static Iso8583Options options(JsonNode testCase) {
        return Iso8583Options.defaults()
                .withCharset(Vectors.charset(testCase.get("encoding").asText()))
                .withHexBitmap(testCase.get("hex_bitmap").asBoolean());
    }

    static {
        // Guards against silently testing against an older generated file.
        if (!Vectors.cardutilVersion().equals("0.7.3")) {
            System.err.println(
                    "Vectors came from cardutil "
                            + Vectors.cardutilVersion()
                            + ", not the 0.7.3 this port was written against.");
        }
    }
}
